---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Homelab Dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
  # url: https://b4bz.io
  # style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  # title: "Welcome to Vivaldi! "
    # icon: "fa fa-grin"
    # content: "Hi! Welcome to my homelab!"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: "Homer Documentation"
    icon: "fas fa-file-alt"
    url: "https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media"
    icon: "fas fa-cloud"
    items:
      - name: "File Browser"
        logo: "assets/tools/filebrowser.svg"
        subtitle: "Main Data Storage"
        # tag: "app"
        keywords: ""
        url: "https://vivaldi.fritz.box:8080"
        target: "_blank"
      - name: "Navidrome"
        logo: "assets/tools/navidrome.svg"
        subtitle: "Music Management"
        url: "https://vivaldi.fritz.box:4533"
        target: "_blank"
        endpoint: "https://vivaldi.fritz.box:4533"
      - name: "Syncthing"
        logo: "https://upload.wikimedia.org/wikipedia/commons/5/57/Syncthing_Logo.svg"
        url: "https://vivaldi.fritz.box:8384"
        target: "_blank"
      - name: "Metube"
        logo: "assets/tools/metube.png"
        url: "https://vivaldi.fritz.box:8090"
        target: "_blank"
      - name: "Jellyfin"
        logo: "assets/logos/jellyfin.svg"
        url: "http://vivaldi.fritz.box:8096"
        target: "_blank"
        type: "Emby"
        apikey: "3f59c560f5b749c0b79f13ee3a3fa188"
        libraryType: "movies"
      - name: "Photoprism"
        logo: "assets/logos/photoprism.svg"
        url: "https://vivaldi.fritz.box:2352"
      - name: "Paperless"
        logo: "assets/logos/paperless.svg"
        url: "https://vivaldi.fritz.box:9000"
        target: "_blank"
        type: "PaperlessNG"
        apikey: "45d936a9879e96314097a187f2c0054babcda803"
  - name: "Programming"
    icon: "fas fa-cloud"
    items:
      - name: "Gitea"
        logo: "assets/tools/gitea.svg"
        url: "https://vivaldi.fritz.box:3001"
      - name: "Grafana"
        logo: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Grafana_icon.svg"
        url: "https://vivaldi.fritz.box:2343"
  - name: "Socials"
    icon: "fas fa-circle-user"
    items:
      - name: "GitHub"
        url: "https://github.com/mjwcodr"
        icon: "fas fa-brands fa-github-alt"
  - name: "Local Services"
    icon: "fas fa-cloud"
    items:
      - name: "Fritz!Box"
        logo: "https://upload.wikimedia.org/wikipedia/de/6/68/Fritz%21_Logo.svg"
        url: "http://fritz.box"
      - name: "Vikunja"
        subtitle: "Task Management"
        logo: "assets/logos/vikunja.svg"
        url: "https://vivaldi.fritz.box:3456"
  - name: "Weather"
    icons: "fas fa-cloud"
    items:
      - name: "Weather"
        location: "Berlin" # your location.
        locationId: "2950159" # Optional: Specify OpenWeatherMap city ID for better accuracy
        apikey: "70df66d75854665fa3de857561a8b785" # insert your own API key here. Request one from https://openweathermap.org/api.
        units: "metric" # units to display temperature. Can be one of: metric, imperial, kelvin. Defaults to kelvin.
        background: "square" # choose which type of background you want behind the image. Can be one of: square, circle, none. Defaults to none.
        type: "OpenWeather"
